CREATE DATABASE IF NOT EXISTS javaDB;
USE javaDB;

DROP TABLE IF EXISTS monster;
CREATE TABLE IF NOT EXISTS monster (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

